apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
  namespace: tp-namespace
spec:
  storageClassName: standard 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
